CREATE DATABASE IF NOT EXISTS FYP;
USE FYP;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,  -- bcrypt hashes are always 60 characters
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 